# Generated by Django 5.1.15 on 2026-06-13 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('feature', 'Feature'), ('remediation', 'Remediation'), ('ci', 'CI'), ('review', 'Review'), ('chore', 'Chore')], default='feature', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('output', models.TextField(blank=True)),
                ('result_summary', models.TextField(blank=True)),
                ('num_turns', models.IntegerField(default=0)),
                ('cost_usd', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Worktree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('base_branch', models.CharField(default='main', max_length=200)),
                ('base_commit', models.CharField(blank=True, max_length=64)),
                ('path', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('creating', 'Creating'), ('active', 'Active'), ('merged', 'Merged'), ('archived', 'Archived')], default='creating', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
