# Generated by Django 5.1.15 on 2026-06-13 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('observability', '0001_initial'),
        ('projects', '0001_initial'),
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='observability.incident'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='projects.project'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='pull_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='vcs.pullrequest'),
        ),
        migrations.AddField(
            model_name='worktree',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worktrees', to='projects.project'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='worktree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='agents.worktree'),
        ),
    ]
