# Generated by Django 5.1.15 on 2026-06-13 18:23

import django.db.models.deletion
from django.db import migrations, models


def backfill_org(apps, schema_editor):
    """Best-effort: stamp org on existing AgentRun/Worktree rows from their
    related project's org. projects.Project may not have an org field yet, so
    guard with getattr and leave org=None where unavailable."""
    AgentRun = apps.get_model("agents", "AgentRun")
    Worktree = apps.get_model("agents", "Worktree")

    for model in (AgentRun, Worktree):
        for row in model.objects.select_related("project").filter(org__isnull=True):
            project = getattr(row, "project", None)
            org = getattr(project, "org", None) if project is not None else None
            if org is not None:
                model.objects.filter(pk=row.pk).update(org=org)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.org'),
        ),
        migrations.AddField(
            model_name='worktree',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.org'),
        ),
        migrations.RunPython(backfill_org, noop),
    ]
