# Generated by Django 5.1.15 on 2026-06-13 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentrun_pid_alter_agentrun_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentrun',
            name='pid',
        ),
        migrations.AlterField(
            model_name='agentrun',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
