# Generated by Django 5.1.15 on 2026-06-13 16:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('repo_url', models.CharField(blank=True, max_length=500)),
                ('local_path', models.CharField(blank=True, max_length=1000)),
                ('default_branch', models.CharField(default='main', max_length=200)),
                ('framework', models.CharField(default='generic', max_length=50)),
                ('run_command', models.CharField(blank=True, max_length=500)),
                ('install_command', models.CharField(blank=True, max_length=500)),
                ('app_subdir', models.CharField(blank=True, default='', max_length=300)),
                ('status', models.CharField(choices=[('importing', 'Importing'), ('ready', 'Ready'), ('failed', 'Failed')], default='importing', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('import_log', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
