# Generated by Django 5.1.15 on 2026-06-13 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_org_alter_project_slug_project_uniq_org_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=80)),
                ('order', models.IntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('detail', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_steps', to='projects.project')),
            ],
            options={
                'ordering': ['project', 'order'],
                'unique_together': {('project', 'key')},
            },
        ),
    ]
