# Generated by Django 5.1.15 on 2026-06-13 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deploys', '0001_initial'),
        ('projects', '0001_initial'),
        ('vcs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('sev1', 'SEV1 — Critical'), ('sev2', 'SEV2 — Major'), ('sev3', 'SEV3 — Minor')], default='sev2', max_length=10)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('acknowledged', 'Acknowledged'), ('remediating', 'Remediating'), ('resolved', 'Resolved')], default='firing', max_length=20)),
                ('signature', models.CharField(blank=True, db_index=True, max_length=200)),
                ('error_type', models.CharField(blank=True, max_length=200)),
                ('error_message', models.TextField(blank=True)),
                ('traceback', models.TextField(blank=True)),
                ('suspect_file', models.CharField(blank=True, max_length=500)),
                ('suspect_line', models.IntegerField(blank=True, null=True)),
                ('occurrences', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='deploys.deployment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='projects.project')),
                ('remediation_pr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='vcs.pullrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LogLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=10)),
                ('message', models.TextField()),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.CharField(blank=True, max_length=500)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('latency_ms', models.FloatField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='deploys.deployment')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['deployment', '-ts'], name='observabili_deploym_37293d_idx')],
            },
        ),
        migrations.CreateModel(
            name='MetricPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=80)),
                ('value', models.FloatField()),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='deploys.deployment')),
            ],
            options={
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['deployment', 'name', '-ts'], name='observabili_deploym_9a8ae2_idx')],
            },
        ),
    ]
