# Generated by Django 5.1.15 on 2026-06-13 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('orchestration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.org'),
        ),
    ]
