# Generated by Django 5.1.15 on 2026-06-13 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('staging', 'Staging'), ('prod', 'Production'), ('preview', 'Preview')], default='preview', max_length=20)),
                ('branch', models.CharField(default='main', max_length=200)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('auto_deploy', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='projects.project')),
                ('worktree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environments', to='agents.worktree')),
            ],
            options={
                'ordering': ['project', 'kind', 'name'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('commit_message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('building', 'Building'), ('live', 'Live'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='queued', max_length=20)),
                ('health', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('unhealthy', 'Unhealthy')], default='unknown', max_length=20)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('pid', models.IntegerField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1000)),
                ('log_path', models.CharField(blank=True, max_length=1000)),
                ('build_log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('live_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='deploys.environment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
