# Generated by Django 5.1.15 on 2026-06-13 18:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('deploys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.org'),
        ),
        migrations.AddField(
            model_name='environment',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.org'),
        ),
        migrations.AddField(
            model_name='environment',
            name='runtime',
            field=models.CharField(choices=[('process', 'Process (subprocess)'), ('compose', 'Docker Compose')], default='process', max_length=20),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=253, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('error', 'Error')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='deploys.environment')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.org')),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
        migrations.CreateModel(
            name='EnvVar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField(blank=True)),
                ('is_secret', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='env_vars', to='deploys.environment')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.org')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('environment', 'key')},
            },
        ),
    ]
