# Generated by Django 5.1.15 on 2026-06-13 16:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('base_branch', models.CharField(default='main', max_length=200)),
                ('head_branch', models.CharField(max_length=200)),
                ('head_commit', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('merged', 'Merged'), ('closed', 'Closed')], default='open', max_length=20)),
                ('ci_status', models.CharField(choices=[('none', 'No CI'), ('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='none', max_length=20)),
                ('diff', models.TextField(blank=True)),
                ('files_changed', models.IntegerField(default=0)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('author', models.CharField(default='claude-agent', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('merged_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull_requests', to='projects.project')),
                ('worktree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pull_requests', to='agents.worktree')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
